// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package taskprovider

import (
	"encoding/json"
	"github.com/google/uuid"
)

type RequestsTask struct {
	TaskID        uuid.UUID        `json:"task_id"`
	TaskStatus    string           `json:"task_status"`
	StatusCode    *int             `json:"status_code"`
	Headers       *json.RawMessage `json:"headers"`
	ContentLength *int64           `json:"content_length"`
}
