// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package taskprovider

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddHttpResponseData(ctx context.Context, arg AddHttpResponseDataParams) error
	CreateWithStatus(ctx context.Context, taskStatus string) (CreateWithStatusRow, error)
	GetOne(ctx context.Context, taskID uuid.UUID) (RequestsTask, error)
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) error
}

var _ Querier = (*Queries)(nil)
